ybrusentsov/react-international-phone

.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
packages/docs/docs/03-Subcomponents API/02-CountrySelectorDropdown.md
packages/docs/docs/04-Advanced Usage/02-useWithUiLibs.md
packages/docs/docusaurus.config.js
src/components/CountrySelector/CountrySelector.test.tsx
src/components/CountrySelector/CountrySelector.tsx
src/components/CountrySelector/CountrySelectorDropdown.test.tsx
src/components/CountrySelector/CountrySelectorDropdown.tsx
src/index.ts

- Fixed dropdown close on click while dropdown is open
- Updated exports
- Updated docs
- Added contributing doc, pull request, and issue templates.

Fix dropdown closing, update docs

---

src/components/CountrySelector/CountrySelectorDropdown.test.tsx
src/components/CountrySelector/CountrySelectorDropdown.tsx
src/utils/common/index.ts
src/utils/common/scrollToChild.ts

- Added scrolling of the dropdown to the selected country
- Added relevant tests

Add scrolling of the dropdown to the selected country

---

src/components/CountrySelector/CountrySelector.tsx

If absent it's seen as type="submit", submitting a potential form where the component is used
Do you want me to add a test or something for this "fix" ? :)

Adding type="button" in CountrySelector

---

.commitlintrc
.husky/commit-msg
.releaserc
CONTRIBUTING.md
package.json
pnpm-lock.yaml

- Added changelog generation
- Added commitlint
- Updated contributing.md doc

Add commitlint and changelog generator configs

---

.commitlintrc
.husky/commit-msg
.releaserc
CONTRIBUTING.md
package.json
pnpm-lock.yaml
src/components/CountrySelector/CountrySelector.tsx

Just interactive rebase with commit title change
- Changed `Adding type="button" in CountrySelector` to `fix: add type="button" in CountrySelector`
- Automatic release won't be triggered because the commit title is out of the convention

Hotfix: update the commit title according to the convention

---

packages/docs/docs/01-getting-started.md
packages/docs/docusaurus.config.js
src/components/CountrySelector/CountrySelector.test.tsx
src/components/CountrySelector/CountrySelectorDropdown.test.tsx
src/components/PhoneInput/PhoneInput.test.tsx
src/hooks/__tests__/useHistoryState.test.ts
src/hooks/__tests__/usePhone.test.ts
src/hooks/__tests__/usePhoneValidation.test.ts
src/hooks/__tests__/useTimer.test.ts
src/hooks/usePhoneInput.ts
src/stories/UiLibsExample/components/AntPhone.tsx
src/utils/common/scrollToChild.ts
src/utils/phoneUtils/__tests__/getCursorPosition.test.ts
src/utils/test-utils.ts

- Re-implemented country-selector-dropdown using the native `scrollIntoView` function
- Some tests improvements
- Docs:
- Fixed passing ref to antd-phone example in storybook
- Added installation scripts for yarn and pnpm, added link to footer

Re-implement dropdown scrolling, small test fixes

---

src/components/PhoneInput/PhoneInput.test.tsx
src/hooks/usePhone.ts
src/hooks/usePhoneInput.ts

- Added initial value formatting
- Fixed flash on mount #28

Fix value flickering on mount

---

packages/docs/docs/04-Advanced Usage/02-useWithUiLibs.md
src/hooks/usePhoneInput.ts
src/stories/Demo.stories.tsx
src/stories/UiLibsExample/components/AntPhone.tsx
src/utils/common/scrollToChild.ts

- Added country guess by passed value on initial render
- Reverted scrolling behaviour (found a bug with scroll event bubbling)
- Docs: updated antd example, added links to "Using with UI libraries" page

Fix country guess by passed value on initial render

---

.lintstagedrc
package.json

- Removed node.js version from package.json
- #31 
- Removed husky and lint-staged configs from package.json
- Moved lint-staged config to separate file

Remove node version from package.json

---

src/data/countryData.ts

- Changed Chinese mask to `... .... ....`
- #35 fix

Update Chinese format mask

---

src/hooks/usePhoneInput.ts
src/stories/PhoneInput.stories.tsx

- Set `isInitializedRef.current` to true on the initial render
- Added controlled mode story

Fix the value change handling after the initial render

---

src/components/CountrySelector/CountrySelectorDropdown.test.tsx
src/components/CountrySelector/CountrySelectorDropdown.tsx
src/components/PhoneInput/PhoneInput.test.tsx
src/utils/test-utils.ts

- Added the ability to search in the country-selector dropdown
- Closes #54 
- Added related tests

Add search to CountrySelectorDropdown

---

.eslintignore
.storybook/main.ts
.storybook/static/flags/fr.svg
.storybook/static/flags/jp.svg
.storybook/static/flags/pl.svg
.storybook/static/flags/ua.svg
.stylelintignore
package.json
packages/docs/docs/02-Usage/01-PhoneInput.md
packages/docs/docs/02-Usage/04-CustomCountryFlags/CustomCountryFlagsExample.tsx
packages/docs/docs/02-Usage/04-CustomCountryFlags/index.md
packages/docs/docs/03-Subcomponents API/04-FlagEmoji.md
packages/docs/docs/03-Subcomponents API/index.md
packages/docs/static/flags/fr.svg
packages/docs/static/flags/jp.svg
packages/docs/static/flags/pl.svg
packages/docs/static/flags/ua.svg
src/components/CountrySelector/CountrySelector.tsx
src/components/CountrySelector/CountrySelectorDropdown.tsx
src/components/FlagEmoji/FlagEmoji.style.scss
src/components/FlagEmoji/FlagEmoji.test.tsx
src/components/FlagEmoji/FlagEmoji.tsx
src/components/PhoneInput/PhoneInput.test.tsx
src/components/PhoneInput/PhoneInput.tsx
src/stories/PhoneInput.stories.tsx
src/types.ts

- Added `flags` prop for passing custom flags data
- Updated tests, updated docs
- Closes #79

Add custom country flags rendering

---

src/hooks/usePhoneInput.ts
src/index.ts
src/utils/countryUtils/getCountryMaskFormat.ts
src/utils/countryUtils/index.ts

- renamed `getCountryCurrentFormat` to `getCountryMaskFormat`
- exported `getCountryMaskFormat` function

export `getCountryMaskFormat` helper function

---

packages/docs/docs/02-Usage/01-PhoneInput.md
src/components/PhoneInput/PhoneInput.tsx
src/hooks/usePhoneInput.ts
src/stories/Dev.stories.tsx

- Added ref forwarding to `PhoneInput` component
- Added support for custom input ref to `usePhoneInput`

Add ref forwarding

---

packages/docs/docs/02-Usage/01-PhoneInput.md
packages/docs/docs/02-Usage/02-ModifyCountries.md
packages/docs/docs/03-Subcomponents API/01-CountrySelector.md
packages/docs/docs/03-Subcomponents API/02-CountrySelectorDropdown.md
packages/docs/docs/03-Subcomponents API/03-DialCodePreview.md
packages/docs/docs/03-Subcomponents API/04-FlagEmoji.md
packages/docs/docs/04-Advanced Usage/01-usePhoneInput.md
packages/docs/docs/04-Advanced Usage/02-useWithUiLibs.md
packages/docs/docs/05-Migrations/04-migrate-to-v4.md
packages/docs/package.json
packages/docs/src/components/MuiPhone/MuiPhone.tsx
packages/docs/src/components/MuiPhone/MuiPhoneJSX.jsx
packages/docs/src/components/PropDescription/PropDescription.tsx
packages/docs/src/components/PropDescription/index.ts
pnpm-lock.yaml
src/hooks/usePhoneInput.ts

- Added migration for v4
- Added docs for new features
- Updated format for API properties list
- Updated docusaurus version

Update docs for v4

---

packages/docs/docs/02-Usage/01-PhoneInput.md
src/components/PhoneInput/PhoneInput.tsx

- Added `name`, `required`, `autoFocus`, `onFocus`,  `onBlur` input-props as top level props

Add most used input props as top level props

---

src/data/countryData.ts

Swedish phone numbers shouldn't have dashes/parentheses

---

src/hooks/usePhoneInput.ts

Fix safari autofocus bug

---

packages/docs/docs/04-Advanced Usage/02-useWithUiLibs.md

A small type fix.
This PR closes #128

[docs] Type Fix

---

src/data/countryData.ts

- Added country codes for Puerto Rico #111

Add country codes for Puerto Rico

---

package.json
tsup.config.ts

- Emit single declaration file with tsup
- Fixes #135

Remove unreachable d.ts references

---

package.json
tsconfig.json
tsup.config.ts

- Changed `build` folder to `dist`
- Fixed repo URL in `package.json`

[Build] Change build folder to dist

---

src/components/FlagImage/FlagImage.tsx
src/index.ts

- Exported missing types from index d.ts file
- Fixes #157

Export missing types from root

---

src/data/countryData.ts

Fix german phone format

---

src/data/countryData.ts

- Fixed phone mask for Germany

Fix Germany mask

---

src/components/PhoneInput/PhoneInput.test.tsx
src/data/countryData.ts
src/utils/countryUtils/__tests__/guessCountryByPartialNumber.test.ts

- Add formatting mask and area codes for the Dominican Republic
- Add formatting mask for Puerto Rico
closes #184

Update Dominican Republic and Puerto Rico country data

---

examples/nextjs-server-side-example/package.json
package.json
pnpm-lock.yaml
src/data/countryData.ts

- Added react 19 support
- Updated Philippines format mask

Add React 19 support

---

src/components/CountrySelector/CountrySelectorDropdown.tsx

Add extra classnames for list item states
